name: tests

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
        components: rustfmt

    - name: Install chromium (Ubuntu)
      run: |
        sudo apt update
        sudo apt install --no-install-recommends chromium-browser
        chromium-browser --version
      if: matrix.os == 'ubuntu-latest'

    - name: Install chromium (Windows)
      run: |
        choco install --no-progress chromium
      shell: bash
      if: matrix.os == 'windows-latest'

    - name: Install chromium (macos)
      run: |
        brew install --cask chromium
      if: matrix.os == 'macos-latest'

    - name: Tests
      uses: actions-rs/cargo@v1
      timeout-minutes: 10
      with:
        command: test
        args: --no-fail-fast
      env:
        RUST_LOG: trace
# vim: set ts=2 sts=2 sw=2:
