name: tests

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest
          #- macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
        components: rustfmt

    - name: Install chromium (Ubuntu)
      run: |
        sudo apt update
        sudo apt install chromium-browser
      if: matrix.os == 'ubuntu-latest'

    - name: Install chromium (Windows)
      run: |
        choco install --no-progress chromium
        ls 'C:\Program Files\Chromium\Application'
        'C:\Program Files\Chromium\Application\chrome.exe' --version
        echo 'C:\Program Files\Chromium\Application' >> $GITHUB_PATH
        #chromium --version
      shell: bash
      if: matrix.os == 'windows-latest'

    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast
# vim: set ts=2 sts=2 sw=2:
